<a href="https://colab.research.google.com/github/Anandkajith/Data-Science-lab/blob/main/Titanic_using_nave_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#libraries
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/Titanic_Train.csv')

In [ ]:
df.head()0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#conversion to values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
# 0 - female, 1 - male
df['Sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [ ]:
#conversion to values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df["Embarked"] = label_encoder.fit_transform(df['Embarked'])
# 2-S , 1-Q ,0-c
df['Embarked']

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Name: Embarked, Length: 891, dtype: int64

In [ ]:
#conversion to values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df["Cabin"] = label_encoder.fit_transform(df['Cabin'])
df['Cabin']

0      147
1       81
2      147
3       55
4      147
      ...
886    147
887     30
888    147
889     60
890    147
Name: Cabin, Length: 891, dtype: int64

In [ ]:
#split of features and labels
x=df.drop(['PassengerId','Survived','Ticket','Name'],axis=1)
y=df['Survived']

In [ ]:
#handle missing values
x.fillna(0, inplace=True)
y.fillna(0, inplace=True)

In [ ]:
#model fitting
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [ ]:
model.fit(x,y)

GaussianNB()

In [ ]:
#testing the model
prediction=model.predict(x)
print(prediction)
print(y)

In [ ]:
#prediction
i=int(input("Enter the number"))
sample = [x.values[i]]
pred = model.predict(sample)
res=pred[0]
if res==1:
  print('Survived')
if res==0:
  print('Dead')
print("Actual value" ,y.values[i])

Enter the number3
Survived
Actual value 1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [ ]:
# read test dataset
df2=pd.read_csv('/content/Titanic_Test.csv')

In [ ]:
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df2.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
#conversion to values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df2['Sex'] = label_encoder.fit_transform(df2['Sex'])
# 0 - female, 1 - male
df2['Sex']

0      1
1      0
2      1
3      1
4      0
      ..
413    1
414    0
415    1
416    1
417    1
Name: Sex, Length: 418, dtype: int64

In [ ]:
#conversion to values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df2["Embarked"] = label_encoder.fit_transform(df2['Embarked'])
# 2-S , 1-Q ,0-c
df2['Embarked']

0      1
1      2
2      1
3      2
4      2
      ..
413    2
414    0
415    2
416    2
417    0
Name: Embarked, Length: 418, dtype: int64

In [ ]:
#conversion to values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df2["Cabin"] = label_encoder.fit_transform(df2['Cabin'])
df2['Cabin']

0      76
1      76
2      76
3      76
4      76
       ..
413    76
414    22
415    76
416    76
417    76
Name: Cabin, Length: 418, dtype: int64

In [ ]:
#split of features and labels
x_test=df2.drop(['PassengerId','Ticket','Name'],axis=1)

In [ ]:
#handle missing values
x_test.fillna(0, inplace=True)

In [ ]:
pred=model.predict(x_test)

In [ ]:
#testing
l=[]
for i in pred:
  if i==1:
    l.append("survived")
  else:
    l.append("dead")
print(l)

['dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'dead', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'survived', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'survived', 'survived', 'survived', 'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead']